// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ZKReply.proto

package org.gibsonsec.zk;

public final class ZKReplyObj {
  private ZKReplyObj() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ZKReplyOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 reply = 1 [default = -1];
    boolean hasReply();
    int getReply();
    
    // optional string reply_str = 2;
    boolean hasReplyStr();
    String getReplyStr();
    
    // optional string key = 3;
    boolean hasKey();
    String getKey();
    
    // optional string user = 4;
    boolean hasUser();
    String getUser();
    
    // optional string app = 5;
    boolean hasApp();
    String getApp();
  }
  public static final class ZKReply extends
      com.google.protobuf.GeneratedMessage
      implements ZKReplyOrBuilder {
    // Use ZKReply.newBuilder() to construct.
    private ZKReply(Builder builder) {
      super(builder);
    }
    private ZKReply(boolean noInit) {}
    
    private static final ZKReply defaultInstance;
    public static ZKReply getDefaultInstance() {
      return defaultInstance;
    }
    
    public ZKReply getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.gibsonsec.zk.ZKReplyObj.internal_static_zk_ZKReply_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.gibsonsec.zk.ZKReplyObj.internal_static_zk_ZKReply_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 reply = 1 [default = -1];
    public static final int REPLY_FIELD_NUMBER = 1;
    private int reply_;
    public boolean hasReply() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getReply() {
      return reply_;
    }
    
    // optional string reply_str = 2;
    public static final int REPLY_STR_FIELD_NUMBER = 2;
    private java.lang.Object replyStr_;
    public boolean hasReplyStr() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getReplyStr() {
      java.lang.Object ref = replyStr_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          replyStr_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getReplyStrBytes() {
      java.lang.Object ref = replyStr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        replyStr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string key = 3;
    public static final int KEY_FIELD_NUMBER = 3;
    private java.lang.Object key_;
    public boolean hasKey() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          key_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string user = 4;
    public static final int USER_FIELD_NUMBER = 4;
    private java.lang.Object user_;
    public boolean hasUser() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getUser() {
      java.lang.Object ref = user_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          user_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUserBytes() {
      java.lang.Object ref = user_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        user_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string app = 5;
    public static final int APP_FIELD_NUMBER = 5;
    private java.lang.Object app_;
    public boolean hasApp() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getApp() {
      java.lang.Object ref = app_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          app_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAppBytes() {
      java.lang.Object ref = app_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        app_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      reply_ = -1;
      replyStr_ = "";
      key_ = "";
      user_ = "";
      app_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, reply_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getReplyStrBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getKeyBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getUserBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getAppBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, reply_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getReplyStrBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getKeyBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getUserBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getAppBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.gibsonsec.zk.ZKReplyObj.ZKReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.gibsonsec.zk.ZKReplyObj.ZKReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.gibsonsec.zk.ZKReplyObj.ZKReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.gibsonsec.zk.ZKReplyObj.ZKReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.gibsonsec.zk.ZKReplyObj.ZKReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.gibsonsec.zk.ZKReplyObj.ZKReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.gibsonsec.zk.ZKReplyObj.ZKReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.gibsonsec.zk.ZKReplyObj.ZKReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.gibsonsec.zk.ZKReplyObj.ZKReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.gibsonsec.zk.ZKReplyObj.ZKReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.gibsonsec.zk.ZKReplyObj.ZKReply prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.gibsonsec.zk.ZKReplyObj.ZKReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.gibsonsec.zk.ZKReplyObj.internal_static_zk_ZKReply_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.gibsonsec.zk.ZKReplyObj.internal_static_zk_ZKReply_fieldAccessorTable;
      }
      
      // Construct using org.gibsonsec.zk.ZKReplyObj.ZKReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        reply_ = -1;
        bitField0_ = (bitField0_ & ~0x00000001);
        replyStr_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        user_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        app_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.gibsonsec.zk.ZKReplyObj.ZKReply.getDescriptor();
      }
      
      public org.gibsonsec.zk.ZKReplyObj.ZKReply getDefaultInstanceForType() {
        return org.gibsonsec.zk.ZKReplyObj.ZKReply.getDefaultInstance();
      }
      
      public org.gibsonsec.zk.ZKReplyObj.ZKReply build() {
        org.gibsonsec.zk.ZKReplyObj.ZKReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.gibsonsec.zk.ZKReplyObj.ZKReply buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.gibsonsec.zk.ZKReplyObj.ZKReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.gibsonsec.zk.ZKReplyObj.ZKReply buildPartial() {
        org.gibsonsec.zk.ZKReplyObj.ZKReply result = new org.gibsonsec.zk.ZKReplyObj.ZKReply(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.reply_ = reply_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.replyStr_ = replyStr_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.user_ = user_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.app_ = app_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.gibsonsec.zk.ZKReplyObj.ZKReply) {
          return mergeFrom((org.gibsonsec.zk.ZKReplyObj.ZKReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.gibsonsec.zk.ZKReplyObj.ZKReply other) {
        if (other == org.gibsonsec.zk.ZKReplyObj.ZKReply.getDefaultInstance()) return this;
        if (other.hasReply()) {
          setReply(other.getReply());
        }
        if (other.hasReplyStr()) {
          setReplyStr(other.getReplyStr());
        }
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (other.hasUser()) {
          setUser(other.getUser());
        }
        if (other.hasApp()) {
          setApp(other.getApp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              reply_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              replyStr_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              key_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              user_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              app_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 reply = 1 [default = -1];
      private int reply_ = -1;
      public boolean hasReply() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getReply() {
        return reply_;
      }
      public Builder setReply(int value) {
        bitField0_ |= 0x00000001;
        reply_ = value;
        onChanged();
        return this;
      }
      public Builder clearReply() {
        bitField0_ = (bitField0_ & ~0x00000001);
        reply_ = -1;
        onChanged();
        return this;
      }
      
      // optional string reply_str = 2;
      private java.lang.Object replyStr_ = "";
      public boolean hasReplyStr() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getReplyStr() {
        java.lang.Object ref = replyStr_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          replyStr_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setReplyStr(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        replyStr_ = value;
        onChanged();
        return this;
      }
      public Builder clearReplyStr() {
        bitField0_ = (bitField0_ & ~0x00000002);
        replyStr_ = getDefaultInstance().getReplyStr();
        onChanged();
        return this;
      }
      void setReplyStr(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        replyStr_ = value;
        onChanged();
      }
      
      // optional string key = 3;
      private java.lang.Object key_ = "";
      public boolean hasKey() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setKey(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        key_ = value;
        onChanged();
        return this;
      }
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000004);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      void setKey(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        key_ = value;
        onChanged();
      }
      
      // optional string user = 4;
      private java.lang.Object user_ = "";
      public boolean hasUser() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getUser() {
        java.lang.Object ref = user_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          user_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUser(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        user_ = value;
        onChanged();
        return this;
      }
      public Builder clearUser() {
        bitField0_ = (bitField0_ & ~0x00000008);
        user_ = getDefaultInstance().getUser();
        onChanged();
        return this;
      }
      void setUser(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        user_ = value;
        onChanged();
      }
      
      // optional string app = 5;
      private java.lang.Object app_ = "";
      public boolean hasApp() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getApp() {
        java.lang.Object ref = app_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          app_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setApp(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        app_ = value;
        onChanged();
        return this;
      }
      public Builder clearApp() {
        bitField0_ = (bitField0_ & ~0x00000010);
        app_ = getDefaultInstance().getApp();
        onChanged();
        return this;
      }
      void setApp(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        app_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:zk.ZKReply)
    }
    
    static {
      defaultInstance = new ZKReply(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:zk.ZKReply)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_zk_ZKReply_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_zk_ZKReply_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rZKReply.proto\022\002zk\"W\n\007ZKReply\022\021\n\005reply\030" +
      "\001 \001(\005:\002-1\022\021\n\treply_str\030\002 \001(\t\022\013\n\003key\030\003 \001(" +
      "\t\022\014\n\004user\030\004 \001(\t\022\013\n\003app\030\005 \001(\tB\036\n\020org.gibs" +
      "onsec.zkB\nZKReplyObj"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_zk_ZKReply_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_zk_ZKReply_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_zk_ZKReply_descriptor,
              new java.lang.String[] { "Reply", "ReplyStr", "Key", "User", "App", },
              org.gibsonsec.zk.ZKReplyObj.ZKReply.class,
              org.gibsonsec.zk.ZKReplyObj.ZKReply.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
